trigger:
  - main

stages:
- stage: SemanticVersion
  jobs:
  - job: SemanticVersion
    displayName: Bump Semantic Version
    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        fetchDepth: 0

      - script: |
          pip install commitizen
        displayName: 'Install Commitizen'

      - task: PowerShell@2
        displayName: 'Bump version & update CHANGELOG.md'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Configuring git author info.." -ForegroundColor Cyan
            git config user.email "Azure DevOps pipeline"
            git config user.name "Azure.Devops@pipeline.com"
            git fetch --all
            git switch $(basename $(Build.SourceBranch))

            Write-Host "Running Commitizen bump.." -ForegroundColor Cyan
            cz bump --yes
            git push --tags origin HEAD:main
