locals {
  short_codes = {
    "eastasia"           = "asea" # Asia
    "southeastasia"      = "asse" # East Asia
    "australiacentral2"  = "auc2" # Australia Central 2
    "australiacentral"   = "auc"  # Australia Central
    "australiaeast"      = "aue"  # Australia East
    "australiasoutheast" = "ause" # Australia Southeast
    "brazilsouth"        = "brs"  # Brazil South
    "brazilsoutheast"    = "brse" # Brazil Southeast
    "canadacentral"      = "cac"  # Canada Central
    "canadaeast"         = "cae"  # Canada East
    "chinaeast2"         = "cne2" # China East 2
    "chinaeast3"         = "cne3" # China East 3
    "chinaeast"          = "cne"  # China East
    "chinanorth2"        = "cnn2" # China North 2
    "chinanorth3"        = "cnn3" # China North 3
    "chinanorth"         = "cnn"  # China North
    "northeurope"        = "eun"  # North Europe
    "westeurope"         = "euw"  # West Europe
    "francecentral"      = "frc"  # France Central
    "francesouth"        = "frs"  # France South
    "germanycentral"     = "gce"  # Germany Central
    "germanynortheast"   = "gne"  # Germany Northeast
    "germanynorth"       = "gno"  # Germany North
    "germanywestcentral" = "gwc"  # Germany West Central
    "centralindia"       = "inc"  # Central India
    "southindia"         = "ins"  # South India
    "westindia"          = "inw"  # West India
    "israelcentral"      = "ilc"  # Israel Central
    "italynorth"         = "itn"  # Italy North
    "japaneast"          = "jpe"  # Japan East
    "japanwest"          = "jpw"  # Japan West
    "koreacentral"       = "krc"  # Korea Central
    "koreasouth"         = "krs"  # Korea South
    "mexicocentral"      = "mxc"  # Mexico Central
    "norwayeast"         = "noe"  # Norway East
    "norwaywest"         = "now"  # Norway West
    "polandcentral"      = "polc" # Poland Central
    "qatarcentral"       = "qatc" # Qatar Central
    "southafricanorth"   = "san"  # South Africa North
    "southafricawest"    = "saw"  # South Africa West
    "spaincentral"       = "spc"  # Spain Central
    "swedencentral"      = "swec" # Sweden Central
    "swedensouth"        = "swes" # Sweden South
    "switzerlandnorth"   = "swn"  # Switzerland North
    "switzerlandwest"    = "sww"  # Switzerland West
    "uaecentral"         = "uaec" # UAE Central
    "uaenorth"           = "uaen" # UAE North
    "uksouth"            = "uks"  # UK South
    "ukwest"             = "ukw"  # UK West
    "centralus"          = "usc"  # Central US
    "eastus2"            = "use2" # East US 2
    "eastus"             = "use"  # East US
    "northcentralus"     = "usnc" # North Central US
    "southcentralus"     = "ussc" # South Central US
    "westus2"            = "usw2" # West US 2
    "westus3"            = "usw3" # West US 3
    "westcentralus"      = "uswc" # West Central US
    "westus"             = "usw"  # West US

    # Global/continental zones
    "asia"        = "asia" # Asia
    "asiapacific" = "apac" # Asia Pacific
    "australia"   = "aus"  # Australia
    "brazil"      = "bra"  # Brazil
    "canada"      = "can"  # Canada
    "europe"      = "eu"   # Europe
    "global"      = "glob" # Global
    "india"       = "ind"  # India
    "japan"       = "jap"  # Japan
    "korea"       = "kor"  # Korea
    "norway"      = "nor"  # Norway
    "singapore"   = "sgp"  # Singapore
    "sweden"      = "swe"  # Sweden
    "uk"          = "uk"   # United Kingdom
    "us"          = "us"   # United States
  }
}
